/**
 * @file App data definitions
 */

export const CORE_APPS = [
    {
        id: 'account',
        text: 'Account',
        href: 'https://myaccount.google.com',
        position: '0px -2088px',
    },
    {
        id: 'search',
        text: 'Search',
        href: 'https://www.google.com',
        position: '0px -812px',
    },
    {
        id: 'maps',
        text: 'Maps',
        href: 'https://maps.google.com',
        position: '0px -2146px',
    },
    {
        id: 'youtube',
        text: 'YouTube',
        href: 'https://www.youtube.com',
        position: '0px -1102px',
    },
    {
        id: 'news',
        text: 'News',
        href: 'https://news.google.com',
        position: '0px -232px',
    },
    {
        id: 'gmail',
        text: 'Gmail',
        href: 'https://mail.google.com/mail/',
        position: '0px -522px',
    },
    {
        id: 'meet',
        text: 'Meet',
        href: 'https://meet.google.com',
        position: '0px -1856px',
    },
    {
        id: 'chat',
        text: 'Chat',
        href: 'https://chat.google.com',
        position: '0px -2494px',
    },
    {
        id: 'contacts',
        text: 'Contacts',
        href: 'https://contacts.google.com',
        position: '0px -464px',
    },
];

export const EXTRA_APPS = [
    {
        id: 'drive',
        text: 'Drive',
        href: 'https://drive.google.com',
        position: '0px -2030px',
    },
    {
        id: 'calendar',
        text: 'Calendar',
        href: 'https://calendar.google.com/calendar',
        position: '0px -1334px',
    },
    {
        id: 'play',
        text: 'Play',
        href: 'https://play.google.com',
        position: '0px -1798px',
    },
    {
        id: 'translate',
        text: 'Translate',
        href: 'https://translate.google.com',
        position: '0px -986px',
    },
    {
        id: 'photos',
        text: 'Photos',
        href: 'https://photos.google.com',
        position: '0px -1682px',
    },
    {
        id: 'chrome',
        text: 'Chrome',
        href: 'https://www.google.com/chrome',
        position: '0px -2552px',
    },
    {
        id: 'shopping',
        text: 'Shopping',
        href: 'https://www.google.com/shopping',
        position: '0px -2436px',
    },
    {
        id: 'finance',
        text: 'Finance',
        href: 'https://www.google.com/finance',
        position: '0px -580px',
    },
    {
        id: 'docs',
        text: 'Docs',
        href: 'https://docs.google.com/document',
        position: '0px -2204px',
    },
    {
        id: 'sheets',
        text: 'Sheets',
        href: 'https://docs.google.com/spreadsheets',
        position: '0px -406px',
    },
    {
        id: 'slides',
        text: 'Slides',
        href: 'https://docs.google.com/presentation',
        position: '0px -2262px',
    },
    {
        id: 'books',
        text: 'Books',
        href: 'https://books.google.com',
        position: '0px -1392px',
    },
    {
        id: 'blogger',
        text: 'Blogger',
        href: 'https://www.blogger.com',
        position: '0px -2320px',
    },
    {
        id: 'keep',
        text: 'Keep',
        href: 'https://keep.google.com',
        position: '0px -116px',
    },
    {
        id: 'earth',
        text: 'Earth',
        href: 'https://earth.google.com/web/',
        position: '0px -1624px',
    },
    {
        id: 'saved',
        text: 'Saved',
        href: 'https://www.google.com/save',
        position: '0px -1218px',
    },
    {
        id: 'artsAndCulture',
        text: 'Arts & Culture',
        href: 'https://artsandculture.google.com',
        position: '0px -1450px',
    },
    {
        id: 'googleAds',
        text: 'Ads',
        href: 'https://ads.google.com/ups/routing',
        position: '0px -2610px',
    },
    {
        id: 'merchantCenter',
        text: 'Merchant Center',
        href: 'https://merchants.google.com',
        position: '0px -1160px',
    },
    {
        id: 'travel',
        text: 'Travel',
        href: 'https://www.google.com/travel',
        position: '0px -1044px',
    },
    {
        id: 'forms',
        text: 'Forms',
        href: 'https://docs.google.com/forms',
        position: '0px -290px',
    },
    {
        id: 'store',
        text: 'Store',
        href: 'https://store.google.com',
        position: '0px -1276px',
    },
    {
        id: 'chromeWebStore',
        text: 'Chrome Web Store',
        href: 'https://chrome.google.com/webstore',
        position: '0px -2784px',
    },
    {
        id: 'googleFiWireless',
        text: 'Fi Wireless',
        href: 'https://fi.google.com',
        position: '0px -58px',
    },
    {
        id: 'analytics',
        text: 'Analytics',
        href: 'https://analytics.google.com/analytics/web',
        position: '0px -2668px',
    },
    {
        id: 'youtubeMusic',
        text: 'YouTube Music',
        href: 'https://music.youtube.com',
        position: '0px -2726px',
    },
    {
        id: 'notebookLM',
        text: 'NotebookLM',
        href: 'https://notebooklm.google.com',
        position: '0px 0px',
    },
    {
        id: 'voice',
        text: 'Voice',
        href: 'https://voice.google.com',
        position: '0px -348px',
    },
    {
        id: 'classroom',
        text: 'Classroom',
        href: 'https://classroom.google.com',
        position: '0px -638px',
    },
    {
        id: 'tasks',
        text: 'Tasks',
        href: 'https://tasks.google.com',
        position: '0px -696px',
    },
    {
        id: 'vault',
        text: 'Vault',
        href: 'https://vault.google.com',
        position: '0px -754px',
    },
    {
        id: 'passwordManager',
        text: 'Password Manager',
        href: 'https://passwords.google.com',
        position: '0px -870px',
    },
    {
        id: 'googleOne',
        text: 'One',
        href: 'https://one.google.com',
        position: '0px -928px',
    },
    {
        id: 'cloudSearch',
        text: 'Cloud Search',
        href: 'https://cloudsearch.google.com/',
        position: '0px -1508px',
    },
    {
        id: 'googleAdmin',
        text: 'Admin',
        href: 'https://admin.google.com/ac/home',
        position: '0px -1566px',
    },
    {
        id: 'wallet',
        text: 'Wallet',
        href: 'https://wallet.google.com/wallet/home',
        position: '0px -1740px',
    },
    {
        id: 'gemini',
        text: 'Gemini',
        href: 'https://gemini.google.com',
        position: '0px -1914px',
    },
    {
        id: 'myAdCenter',
        text: 'My Ad Center',
        href: 'https://myadcenter.google.com',
        position: '0px -1972px',
    },
    {
        id: 'sites',
        text: 'Sites',
        href: 'https://sites.google.com',
        position: '0px -2378px',
    },
    {
        id: 'vids',
        text: 'Vids',
        href: 'https://docs.google.com/videos',
        position: '0px -2958px',
    },
];
